/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PortfolioIntelligenceRouteImport } from './routes/portfolio-intelligence'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AiFrontDeskRouteImport } from './routes/ai-front-desk'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIntelligenceRoute = PortfolioIntelligenceRouteImport.update({
  id: '/portfolio-intelligence',
  path: '/portfolio-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AiFrontDeskRoute = AiFrontDeskRouteImport.update({
  id: '/ai-front-desk',
  path: '/ai-front-desk',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-front-desk': typeof AiFrontDeskRoute
  '/analytics': typeof AnalyticsRoute
  '/booking': typeof BookingRoute
  '/dashboard': typeof DashboardRoute
  '/platform': typeof PlatformRoute
  '/portfolio-intelligence': typeof PortfolioIntelligenceRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/waitlist': typeof WaitlistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-front-desk': typeof AiFrontDeskRoute
  '/analytics': typeof AnalyticsRoute
  '/booking': typeof BookingRoute
  '/dashboard': typeof DashboardRoute
  '/platform': typeof PlatformRoute
  '/portfolio-intelligence': typeof PortfolioIntelligenceRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/waitlist': typeof WaitlistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-front-desk': typeof AiFrontDeskRoute
  '/analytics': typeof AnalyticsRoute
  '/booking': typeof BookingRoute
  '/dashboard': typeof DashboardRoute
  '/platform': typeof PlatformRoute
  '/portfolio-intelligence': typeof PortfolioIntelligenceRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/waitlist': typeof WaitlistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-front-desk'
    | '/analytics'
    | '/booking'
    | '/dashboard'
    | '/platform'
    | '/portfolio-intelligence'
    | '/pricing'
    | '/sitemap.xml'
    | '/team'
    | '/waitlist'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-front-desk'
    | '/analytics'
    | '/booking'
    | '/dashboard'
    | '/platform'
    | '/portfolio-intelligence'
    | '/pricing'
    | '/sitemap.xml'
    | '/team'
    | '/waitlist'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-front-desk'
    | '/analytics'
    | '/booking'
    | '/dashboard'
    | '/platform'
    | '/portfolio-intelligence'
    | '/pricing'
    | '/sitemap.xml'
    | '/team'
    | '/waitlist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiFrontDeskRoute: typeof AiFrontDeskRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BookingRoute: typeof BookingRoute
  DashboardRoute: typeof DashboardRoute
  PlatformRoute: typeof PlatformRoute
  PortfolioIntelligenceRoute: typeof PortfolioIntelligenceRoute
  PricingRoute: typeof PricingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeamRoute: typeof TeamRoute
  WaitlistRoute: typeof WaitlistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio-intelligence': {
      id: '/portfolio-intelligence'
      path: '/portfolio-intelligence'
      fullPath: '/portfolio-intelligence'
      preLoaderRoute: typeof PortfolioIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-front-desk': {
      id: '/ai-front-desk'
      path: '/ai-front-desk'
      fullPath: '/ai-front-desk'
      preLoaderRoute: typeof AiFrontDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiFrontDeskRoute: AiFrontDeskRoute,
  AnalyticsRoute: AnalyticsRoute,
  BookingRoute: BookingRoute,
  DashboardRoute: DashboardRoute,
  PlatformRoute: PlatformRoute,
  PortfolioIntelligenceRoute: PortfolioIntelligenceRoute,
  PricingRoute: PricingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeamRoute: TeamRoute,
  WaitlistRoute: WaitlistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
